### ISSUE TITLE
Add GIF or screenshots to your homepage?

### ISSUE THREAD

**Issue by PySimpleGUI** [nngogol/async-desktop-chat#1]
I think your video demo is killer.

It would be great to show people what they get with your code.

I converted your video into a GIF

![video](https://user-images.githubusercontent.com/46163555/81684482-ffd36900-9424-11ea-9ef1-a6015de75e28.gif)

I will post about this in an announcement and include this GIF.  

However, I think maybe I need to start using the WIKI part of the GitHub too.  There should be a "Spotlight" area to point out amazing applications.  There is a "User Screenshots" issue that's used now too. but you have to know where it is.  The WIKI is right there.  

SO many things can be improved, but I can only do so many of them.  And that's OK. I just have to pick which.

**Comment by nngogol** [comment]
Thank you for making gif! Indeed, ***Spotlight area*** is a great idea.
So, I fixed, by ADDING your gif n
https://github.com/nngogol/async-desktop-chat/commit/bd74a79876745e305c50f8031129d1ab129ac41c
